/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MangaMangaIdRouteImport } from './routes/manga.$mangaId'
import { Route as GlobalGlobalIdRouteImport } from './routes/global.$globalId'
import { Route as ReadMangaIdChapterIdRouteImport } from './routes/read.$mangaId.$chapterId'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaMangaIdRoute = MangaMangaIdRouteImport.update({
  id: '/manga/$mangaId',
  path: '/manga/$mangaId',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalGlobalIdRoute = GlobalGlobalIdRouteImport.update({
  id: '/global/$globalId',
  path: '/global/$globalId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadMangaIdChapterIdRoute = ReadMangaIdChapterIdRouteImport.update({
  id: '/read/$mangaId/$chapterId',
  path: '/read/$mangaId/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/import': typeof ImportRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/global/$globalId': typeof GlobalGlobalIdRoute
  '/manga/$mangaId': typeof MangaMangaIdRoute
  '/read/$mangaId/$chapterId': typeof ReadMangaIdChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/import': typeof ImportRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/global/$globalId': typeof GlobalGlobalIdRoute
  '/manga/$mangaId': typeof MangaMangaIdRoute
  '/read/$mangaId/$chapterId': typeof ReadMangaIdChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/import': typeof ImportRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/global/$globalId': typeof GlobalGlobalIdRoute
  '/manga/$mangaId': typeof MangaMangaIdRoute
  '/read/$mangaId/$chapterId': typeof ReadMangaIdChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/import'
    | '/settings'
    | '/trash'
    | '/global/$globalId'
    | '/manga/$mangaId'
    | '/read/$mangaId/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/import'
    | '/settings'
    | '/trash'
    | '/global/$globalId'
    | '/manga/$mangaId'
    | '/read/$mangaId/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/discover'
    | '/import'
    | '/settings'
    | '/trash'
    | '/global/$globalId'
    | '/manga/$mangaId'
    | '/read/$mangaId/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  ImportRoute: typeof ImportRoute
  SettingsRoute: typeof SettingsRoute
  TrashRoute: typeof TrashRoute
  GlobalGlobalIdRoute: typeof GlobalGlobalIdRoute
  MangaMangaIdRoute: typeof MangaMangaIdRoute
  ReadMangaIdChapterIdRoute: typeof ReadMangaIdChapterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$mangaId': {
      id: '/manga/$mangaId'
      path: '/manga/$mangaId'
      fullPath: '/manga/$mangaId'
      preLoaderRoute: typeof MangaMangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global/$globalId': {
      id: '/global/$globalId'
      path: '/global/$globalId'
      fullPath: '/global/$globalId'
      preLoaderRoute: typeof GlobalGlobalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$mangaId/$chapterId': {
      id: '/read/$mangaId/$chapterId'
      path: '/read/$mangaId/$chapterId'
      fullPath: '/read/$mangaId/$chapterId'
      preLoaderRoute: typeof ReadMangaIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  ImportRoute: ImportRoute,
  SettingsRoute: SettingsRoute,
  TrashRoute: TrashRoute,
  GlobalGlobalIdRoute: GlobalGlobalIdRoute,
  MangaMangaIdRoute: MangaMangaIdRoute,
  ReadMangaIdChapterIdRoute: ReadMangaIdChapterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
